version: "3.9"
services:
  website:
    build:
      context: .
      dockerfile: web-client/Dockerfile
    ports:
      - "9001:9000"
    depends_on:
      - main-server
  main-server:
    build:
      context: .
      dockerfile: main-server/Dockerfile
    ports:
      - "12345:12345"
    environment: 
      - MONGODB_URI=mongodb://root:uncrackable@document-db
    networks:
        - grpc
        - db
    depends_on:
      - vault
      - recommendation
      - init-db-job
  vault:
    build:
      context: .
      dockerfile: vault/Dockerfile
    networks:
        - grpc
  recommendation:
    build:
      context: .
      dockerfile: recommendation/Dockerfile
    networks:
        - grpc
  init-db-job:
    build:
        context: .
        dockerfile: init-db/Dockerfile
    environment: 
      - MONGODB_URI=mongodb://root:uncrackable@document-db
    networks:
      - db
    depends_on:
      - mongo
  document-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=uncrackable
    networks:
      - db
    expose:
      - 27017
networks:
    grpc:
    db: