version: "3.9"
services:
  website:
    build:
      context: .
      dockerfile: web-client/Dockerfile
    ports:
      - "9001:9000"
    depends_on:
      - main-server
  main-server:
    build:
      context: .
      dockerfile: main-server/Dockerfile
    ports:
      - "12345:12345"
    networks:
        - grpc-demo
    depends_on:
      - vault
      - recommendation
      - init-db-job
    environment:
      MONGODB_URI: mongodb://root:notsecurebutwhatever@mongo:27017/
  vault:
    build:
      context: .
      dockerfile: vault/Dockerfile
    networks:
        - grpc-demo
  recommendation:
    build:
      context: .
      dockerfile: recommendation/Dockerfile
    networks:
        - grpc-demo
  init-db-job:
    build:
        context: .
        dockerfile: init-db/Dockerfile
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://root:notsecurebutwhatever@mongo:27017/
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: notsecurebutwhatever
networks:
    grpc-demo: