# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vault_pb2 as vault__pb2


class VaultManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_secret = channel.unary_unary(
                '/VaultManager/get_secret',
                request_serializer=vault__pb2.VaultRequest.SerializeToString,
                response_deserializer=vault__pb2.VaultResponse.FromString,
                )


class VaultManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_secret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_secret': grpc.unary_unary_rpc_method_handler(
                    servicer.get_secret,
                    request_deserializer=vault__pb2.VaultRequest.FromString,
                    response_serializer=vault__pb2.VaultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VaultManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VaultManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_secret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/VaultManager/get_secret',
            vault__pb2.VaultRequest.SerializeToString,
            vault__pb2.VaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
