# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvault.proto\"=\n\x0cVaultRequest\x12\x13\n\x0bvault_token\x18\x01 \x01(\t\x12\x18\n\x10requested_secret\x18\x02 \x01(\t\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"/\n\rVaultResponse\x12\x1e\n\x07secrets\x18\x01 \x03(\x0b\x32\r.KeyValuePair2;\n\x0cVaultManager\x12+\n\nget_secret\x12\r.VaultRequest\x1a\x0e.VaultResponseb\x06proto3')



_VAULTREQUEST = DESCRIPTOR.message_types_by_name['VaultRequest']
_KEYVALUEPAIR = DESCRIPTOR.message_types_by_name['KeyValuePair']
_VAULTRESPONSE = DESCRIPTOR.message_types_by_name['VaultResponse']
VaultRequest = _reflection.GeneratedProtocolMessageType('VaultRequest', (_message.Message,), {
  'DESCRIPTOR' : _VAULTREQUEST,
  '__module__' : 'vault_pb2'
  # @@protoc_insertion_point(class_scope:VaultRequest)
  })
_sym_db.RegisterMessage(VaultRequest)

KeyValuePair = _reflection.GeneratedProtocolMessageType('KeyValuePair', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUEPAIR,
  '__module__' : 'vault_pb2'
  # @@protoc_insertion_point(class_scope:KeyValuePair)
  })
_sym_db.RegisterMessage(KeyValuePair)

VaultResponse = _reflection.GeneratedProtocolMessageType('VaultResponse', (_message.Message,), {
  'DESCRIPTOR' : _VAULTRESPONSE,
  '__module__' : 'vault_pb2'
  # @@protoc_insertion_point(class_scope:VaultResponse)
  })
_sym_db.RegisterMessage(VaultResponse)

_VAULTMANAGER = DESCRIPTOR.services_by_name['VaultManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VAULTREQUEST._serialized_start=15
  _VAULTREQUEST._serialized_end=76
  _KEYVALUEPAIR._serialized_start=78
  _KEYVALUEPAIR._serialized_end=120
  _VAULTRESPONSE._serialized_start=122
  _VAULTRESPONSE._serialized_end=169
  _VAULTMANAGER._serialized_start=171
  _VAULTMANAGER._serialized_end=230
# @@protoc_insertion_point(module_scope)
