# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\"F\n\x04Task\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1b\n\x08priority\x18\x03 \x01(\x0e\x32\t.Priority\":\n\x0bTaskRequest\x12\x10\n\x08\x61ssignee\x18\x01 \x01(\t\x12\x19\n\nopen_tasks\x18\x02 \x03(\x0b\x32\x05.Task\"#\n\x0cTaskResponse\x12\x13\n\x04task\x18\x01 \x01(\x0b\x32\x05.Task*)\n\x08Priority\x12\x07\n\x03LOW\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x08\n\x04HIGH\x10\x02\x32L\n\x15RecommendationManager\x12\x33\n\x14\x63hoose_task_for_user\x12\x0c.TaskRequest\x1a\r.TaskResponseb\x06proto3')

_PRIORITY = DESCRIPTOR.enum_types_by_name['Priority']
Priority = enum_type_wrapper.EnumTypeWrapper(_PRIORITY)
LOW = 0
MEDIUM = 1
HIGH = 2


_TASK = DESCRIPTOR.message_types_by_name['Task']
_TASKREQUEST = DESCRIPTOR.message_types_by_name['TaskRequest']
_TASKRESPONSE = DESCRIPTOR.message_types_by_name['TaskResponse']
Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:Task)
  })
_sym_db.RegisterMessage(Task)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESPONSE,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:TaskResponse)
  })
_sym_db.RegisterMessage(TaskResponse)

_RECOMMENDATIONMANAGER = DESCRIPTOR.services_by_name['RecommendationManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRIORITY._serialized_start=194
  _PRIORITY._serialized_end=235
  _TASK._serialized_start=25
  _TASK._serialized_end=95
  _TASKREQUEST._serialized_start=97
  _TASKREQUEST._serialized_end=155
  _TASKRESPONSE._serialized_start=157
  _TASKRESPONSE._serialized_end=192
  _RECOMMENDATIONMANAGER._serialized_start=237
  _RECOMMENDATIONMANAGER._serialized_end=313
# @@protoc_insertion_point(module_scope)
